### ISSUE TITLE
had to add -std=c99 to makefile to build

### ISSUE THREAD

**Issue by rghvdberg** [ycollet/vopa#1]
build fails after cloning from git

> ~/build/vopa $ make
> gcc -Wall -O3 -ffast-math -lm `pkg-config --cflags --libs lv2core` -fPIC -c vopast.c -o vopast.o
> In file included from vopast.h:33:0,
>                  from vopast.c:22:
> /usr/lib/lv2/atom.lv2/util.h: In function ‘lv2_atom_object_query’:
> /usr/lib/lv2/atom.lv2/util.h:336:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
>   for (LV2_Atom_Object_Query\* q = query; q->key; ++q) {
>   ^
> /usr/lib/lv2/atom.lv2/util.h:336:2: note: use option -std=c99 or -std=gnu99 to compile your code
> /usr/lib/lv2/atom.lv2/util.h:340:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
>   LV2_ATOM_OBJECT_FOREACH(object, prop) {
>  ... etc ...
>    ^
> make: **\* [vopast.o] Fout 1

when adding -std-c99 to CFLAGS += in the Makefile it build
CFLAGS += -Wall -O3 -ffast-math -lm `pkg-config --cflags --libs lv2core` -fPIC **-std=c99**

now lets see if it actually works :wink:

**Comment by rghvdberg** [comment]
it works :+1:

**Comment by ycollet** [comment]
Thanks for the report. I just added the flag in the Makefile.
Best regards,
YC
