### ISSUE TITLE
decrease in volume when plugin is inserted

### ISSUE THREAD

**Issue by rghvdberg** [ycollet/vopa#2]
When I add the plugin in Qtractor the volume lowers (not touching the faders).
It's about 3 db lower

**Comment by ycollet** [comment]
OK, I see.
I changed the volume default divider (from 127 to 100). I understand better why I need to use 100 instead of 127 ...
Can you try with this change ?

**Comment by rghvdberg** [comment]
yup, working ok !
we can close this one

**Comment by ycollet** [comment]
Thanks again for all your tests.

Best regards,

YC
