### ISSUE TITLE
metadata does not validate

### ISSUE THREAD

**Issue by ventosus** [ycollet/vopa#3]
This plugin's metadata does not validate.

```
error: Object not in property range:
       https://github.com/ycollet/vopa:VoPaMo
       http://lv2plug.in/ns/lv2core#optionalFeature
       http://lv2plug.in/ns/lv2core#hardRtCapable
note: Range is <http://lv2plug.in/ns/lv2core#Feature>
error: Object not in property range:
       https://github.com/ycollet/vopa:VoPaMo
       http://lv2plug.in/ns/lv2core#project
       http://lv2plug.in/ns/lv2
note: Range is <http://usefulinc.com/ns/doap#Project>
error: Object not in property range:
       https://github.com/ycollet/vopa:VoPaSt
       http://lv2plug.in/ns/lv2core#optionalFeature
       http://lv2plug.in/ns/lv2core#hardRtCapable
note: Range is <http://lv2plug.in/ns/lv2core#Feature>
error: Object not in property range:
       https://github.com/ycollet/vopa:VoPaSt
       http://lv2plug.in/ns/lv2core#project
       http://lv2plug.in/ns/lv2
note: Range is <http://usefulinc.com/ns/doap#Project>
Found 4 errors among 35 files (checked 1460 restrictions)
```

e.g. you want to use http://lv2plug.in/ns/lv2core/#hardRTCapable and define your own doap:project.

here's how to validate plugins prior to release:
http://lv2plug.in/pages/validating-lv2-data.html

**Comment by ycollet** [comment]
Thanks for this link. I will investigate this ASAP.
Best regards,
YC

**Comment by ycollet** [comment]
Can you past the command line you use to validate the ttl file ?

**Comment by ycollet** [comment]
Finally, I found a good way to isolate main errors:

First I run sord_validate on the reference files:

```
sord_validate `find /opt/lv2core-devel -name "*.ttl"` `find /opt/drobilla-devel -name "*.ttl"` > base.txt 2>&1
```

Then I run sord_validate on the file I need to inspect:

```
sord_validate `find /opt/lv2core-devel -name "*.ttl"` `find /opt/drobilla-devel -name "*.ttl"` vopamo.ttl > vopamo.txt 2>&1
```

And then, I do a diff:

```
meld base.txt vopamo.txt
```

And the main errors are highlighted.

I close the issue.
Thanks again for the report.

**Comment by ventosus** [comment]
this is the script I use: https://gist.github.com/ventosus/2d1903abd585194f49fc31fd04b0eeaa

```
./lv2validate /usr/local/lib/lv2/vopa/*.ttl
```

here a tutorial on how to validate LV2 plugins: https://media.ccc.de/v/minilac16-ltsmakesomeplugins

**Comment by ycollet** [comment]
Thanks for the links
